# Define WSL aliases for common Linux commands
Set-Alias -Name sed -Value "wsl sed"
Set-Alias -Name awk -Value "wsl awk"
Set-Alias -Name grep -Value "wsl grep"
Set-Alias -Name jq -Value "wsl jq"
Set-Alias -Name find -Value "wsl find"
Set-Alias -Name sort -Value "wsl sort"
Set-Alias -Name uniq -Value "wsl uniq"
Set-Alias -Name cut -Value "wsl cut"
Set-Alias -Name wc -Value "wsl wc"
Set-Alias -Name tr -Value "wsl tr"
Set-Alias -Name xargs -Value "wsl xargs"
Set-Alias -Name curl -Value "wsl curl"
Set-Alias -Name awk -Value "wsl awk"
Set-Alias -Name tar -Value "wsl tar"
Set-Alias -Name head -Value "wsl head"
Set-Alias -Name more -Value "wsl more"
Set-Alias -Name wget -Value "wsl wget"
